server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    url: jdbc:h2:mem:studentsdatabase;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true